// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATaQ5ksTq1grYlndndp891HqLpVKR3OWM',
    appId: '1:835639496992:web:33b9b4e2aea8e084ef4745',
    messagingSenderId: '835639496992',
    projectId: 'legalhub-bfbf3',
    authDomain: 'legalhub-bfbf3.firebaseapp.com',
    storageBucket: 'legalhub-bfbf3.firebasestorage.app',
    measurementId: 'G-6EXRLM2RGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3iX-g40aS8aaCYM4t8T_SQbjhvqq6ZF8',
    appId: '1:835639496992:android:3dfe1a461ae942cdef4745',
    messagingSenderId: '835639496992',
    projectId: 'legalhub-bfbf3',
    storageBucket: 'legalhub-bfbf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wSGyQPmYKcUStZxWfj7nNtDAantkjec',
    appId: '1:835639496992:ios:07c766cac3dd6d6fef4745',
    messagingSenderId: '835639496992',
    projectId: 'legalhub-bfbf3',
    storageBucket: 'legalhub-bfbf3.firebasestorage.app',
    iosClientId: '835639496992-8jeo4hv2m86d8391nuht128mi8i101hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalHubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wSGyQPmYKcUStZxWfj7nNtDAantkjec',
    appId: '1:835639496992:ios:07c766cac3dd6d6fef4745',
    messagingSenderId: '835639496992',
    projectId: 'legalhub-bfbf3',
    storageBucket: 'legalhub-bfbf3.firebasestorage.app',
    iosClientId: '835639496992-8jeo4hv2m86d8391nuht128mi8i101hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalHubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATaQ5ksTq1grYlndndp891HqLpVKR3OWM',
    appId: '1:835639496992:web:d357210c6495b9d4ef4745',
    messagingSenderId: '835639496992',
    projectId: 'legalhub-bfbf3',
    authDomain: 'legalhub-bfbf3.firebaseapp.com',
    storageBucket: 'legalhub-bfbf3.firebasestorage.app',
    measurementId: 'G-D6VLZ8ZF97',
  );
}
